apiVersion: v1
kind: Service
metadata:
  name: backend-django
spec:
  type: ClusterIP
  selector:
    app: backend-django
  ports:
    - port: 8080 # port to external access
      targetPort: 8080 # target port to pod
